DEV := npm run dev
NGROK := ngrok http --url=seasnail-alert-serval.ngrok-free.app 5173

up:
	$(DEV)

ngrok:
	$(NGROK)
#
#const container = params.get("container")
#const viewer_type = params.get("viewer_type")
#const user_image = params.get("user_image")
#const web_server = params.get("web_server")
#const user_name = params.get("user_name")
#const user_stat_id = params.get("user_stat_id")
#const first_start = params.get("first_start")
#const user_gender = params.get("user_gender")
#const ajax = params.get("ajax")
#const logged_user_id = params.get("logged_user_id")
#const sig = params.get("sig")
#const new_sig = params.get("new_sig")
#const group_id = params.get("group_id")
#const apiconnection = params.get("apiconnection")
#const authorized = params.get("authorized")
#const session_key = params.get("session_key")
#const clientLog = params.get("clientLog")
#const session_secret_key = params.get("session_secret_key")
#const auth_sig = params.get("auth_sig")
#const api_server = params.get("api_server")
#const theme = params.get("theme")
#const lang = params.get("lang")
#const ip_geo_location = params.get("ip_geo_location")
#const application_key = params.get("application_key")
#
#console.log("container", container)
#console.log("viewer_type", viewer_type)
#console.log("user_image", user_image)
#console.log("web_server", web_server)
#console.log("user_name", user_name)
#console.log("user_stat_id", user_stat_id)
#console.log("first_start", first_start)
#console.log("user_gender", user_gender)
#console.log("ajax", ajax)
#console.log("logged_user_id", logged_user_id)
#console.log("sig", sig)
#console.log("new_sig", new_sig)
#console.log("group_id", group_id)
#console.log("apiconnection", apiconnection)
#console.log("authorized", authorized)
#console.log("session_key", session_key)
#console.log("clientLog", clientLog)
#console.log("session_secret_key", session_secret_key)
#console.log("auth_sig", auth_sig)
#console.log("api_server", api_server)
#console.log("theme", theme)
#console.log("lang", lang)
#console.log("ip_geo_location", ip_geo_location)
#console.log("application_key", application_key)